// Sample library data + chapter text

const COVER_PALETTES = {
  prideAndPrejudice: { bg: '#5a3a3a', ink: '#f4e9d4', accent: '#c7a45a', style: 'classic' },
  beginningInfinity: { bg: '#0e1a2b', ink: '#e8e3d4', accent: '#d97b3a', style: 'modern' },
  ddia:              { bg: '#d6a429', ink: '#1a1a1a', accent: '#a76b00', style: 'animal' },
  sapiens:           { bg: '#e9dccb', ink: '#1a1a1a', accent: '#9c2b1f', style: 'editorial' },
  meditations:       { bg: '#1a1a18', ink: '#d8c98a', accent: '#7a6a3c', style: 'classic' },
  threeBody:         { bg: '#0a0e1c', ink: '#d8d2c5', accent: '#7a3a3a', style: 'modern' },
  pragmatic:         { bg: '#1c3a5f', ink: '#f4e9d4', accent: '#d97b3a', style: 'editorial' },
  atomicHabits:      { bg: '#f4e9d4', ink: '#1a1a1a', accent: '#3a6a5a', style: 'minimal' },
  selfishGene:       { bg: '#2a2a28', ink: '#e8e3d4', accent: '#a8804a', style: 'minimal' },
  thinkingFastSlow:  { bg: '#e6d6b6', ink: '#1a1a1a', accent: '#5a3a3a', style: 'editorial' },
  walden:            { bg: '#2a3a2a', ink: '#e8e3d4', accent: '#a8804a', style: 'classic' },
  brokenEarth:       { bg: '#3a1818', ink: '#f4e9d4', accent: '#d97b3a', style: 'modern' },
};

const BOOKS = [
  {
    id: 'pp',
    title: 'Pride and Prejudice',
    author: 'Jane Austen',
    year: 1813,
    format: 'EPUB',
    size: '432 KB',
    progress: 0.34,
    lastRead: '2h ago',
    chapters: 61,
    pages: 432,
    currentPage: 147,
    tags: ['Fiction', 'Classics'],
    cover: COVER_PALETTES.prideAndPrejudice,
    highlights: 7,
    bookmarks: 3,
  },
  {
    id: 'bi',
    title: 'The Beginning of Infinity',
    author: 'David Deutsch',
    year: 2011,
    format: 'EPUB',
    size: '1.8 MB',
    progress: 0.62,
    lastRead: 'Yesterday',
    chapters: 18,
    pages: 487,
    currentPage: 302,
    tags: ['Non-fiction', 'Science'],
    cover: COVER_PALETTES.beginningInfinity,
    highlights: 24,
    bookmarks: 5,
  },
  {
    id: 'ddia',
    title: 'Designing Data-Intensive Applications',
    author: 'Martin Kleppmann',
    year: 2017,
    format: 'PDF',
    size: '8.4 MB',
    progress: 0.18,
    lastRead: '3d ago',
    chapters: 12,
    pages: 614,
    currentPage: 111,
    tags: ['Technical', 'Engineering'],
    cover: COVER_PALETTES.ddia,
    highlights: 12,
    bookmarks: 8,
  },
  {
    id: 'sap',
    title: 'Sapiens',
    author: 'Yuval Noah Harari',
    year: 2011,
    format: 'AZW3',
    size: '2.1 MB',
    progress: 0.91,
    lastRead: '1w ago',
    chapters: 20,
    pages: 443,
    currentPage: 403,
    tags: ['Non-fiction', 'History'],
    cover: COVER_PALETTES.sapiens,
    highlights: 41,
    bookmarks: 2,
  },
  {
    id: 'med',
    title: 'Meditations',
    author: 'Marcus Aurelius',
    year: 180,
    format: 'TXT',
    size: '298 KB',
    progress: 0.45,
    lastRead: '4d ago',
    chapters: 12,
    pages: 256,
    currentPage: 115,
    tags: ['Philosophy', 'Classics'],
    cover: COVER_PALETTES.meditations,
    highlights: 18,
    bookmarks: 4,
  },
  {
    id: '3b',
    title: 'The Three-Body Problem',
    author: '刘慈欣',
    year: 2008,
    format: 'EPUB',
    size: '1.2 MB',
    progress: 0.08,
    lastRead: 'Just now',
    chapters: 32,
    pages: 384,
    currentPage: 31,
    tags: ['Fiction', 'Sci-Fi', 'CJK'],
    cover: COVER_PALETTES.threeBody,
    highlights: 2,
    bookmarks: 1,
  },
  {
    id: 'prag',
    title: 'The Pragmatic Programmer',
    author: 'David Thomas & Andrew Hunt',
    year: 1999,
    format: 'PDF',
    size: '5.7 MB',
    progress: 0.55,
    lastRead: '2d ago',
    chapters: 9,
    pages: 352,
    currentPage: 193,
    tags: ['Technical', 'Career'],
    cover: COVER_PALETTES.pragmatic,
    highlights: 33,
    bookmarks: 11,
  },
  {
    id: 'ah',
    title: 'Atomic Habits',
    author: 'James Clear',
    year: 2018,
    format: 'EPUB',
    size: '714 KB',
    progress: 1.0,
    lastRead: '2w ago',
    chapters: 20,
    pages: 320,
    currentPage: 320,
    tags: ['Non-fiction', 'Self-help'],
    cover: COVER_PALETTES.atomicHabits,
    highlights: 19,
    bookmarks: 6,
  },
  {
    id: 'sg',
    title: 'The Selfish Gene',
    author: 'Richard Dawkins',
    year: 1976,
    format: 'EPUB',
    size: '892 KB',
    progress: 0.0,
    lastRead: 'Never',
    chapters: 13,
    pages: 360,
    currentPage: 1,
    tags: ['Non-fiction', 'Science'],
    cover: COVER_PALETTES.selfishGene,
    highlights: 0,
    bookmarks: 0,
  },
  {
    id: 'tfs',
    title: 'Thinking, Fast and Slow',
    author: 'Daniel Kahneman',
    year: 2011,
    format: 'AZW3',
    size: '1.4 MB',
    progress: 0.22,
    lastRead: '5d ago',
    chapters: 38,
    pages: 499,
    currentPage: 110,
    tags: ['Non-fiction', 'Psychology'],
    cover: COVER_PALETTES.thinkingFastSlow,
    highlights: 8,
    bookmarks: 3,
  },
  {
    id: 'wld',
    title: 'Walden',
    author: 'Henry David Thoreau',
    year: 1854,
    format: 'TXT',
    size: '512 KB',
    progress: 0.0,
    lastRead: 'Never',
    chapters: 18,
    pages: 304,
    currentPage: 1,
    tags: ['Classics', 'Philosophy'],
    cover: COVER_PALETTES.walden,
    highlights: 0,
    bookmarks: 0,
  },
  {
    id: 'be',
    title: 'The Fifth Season',
    author: 'N. K. Jemisin',
    year: 2015,
    format: 'EPUB',
    size: '1.0 MB',
    progress: 0.74,
    lastRead: '12h ago',
    chapters: 23,
    pages: 468,
    currentPage: 346,
    tags: ['Fiction', 'Fantasy'],
    cover: COVER_PALETTES.brokenEarth,
    highlights: 14,
    bookmarks: 7,
  },
];

// Pride & Prejudice — opening (public domain), used as the reader's "current" book
const PP_PAGES = [
  {
    chapter: 'Chapter 1',
    paragraphs: [
      'It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife.',
      'However little known the feelings or views of such a man may be on his first entering a neighbourhood, this truth is so well fixed in the minds of the surrounding families, that he is considered as the rightful property of some one or other of their daughters.',
      '"My dear Mr. Bennet," said his lady to him one day, "have you heard that Netherfield Park is let at last?"',
      'Mr. Bennet replied that he had not.',
      '"But it is," returned she; "for Mrs. Long has just been here, and she told me all about it."',
      'Mr. Bennet made no answer.',
      '"Do not you want to know who has taken it?" cried his wife impatiently.',
      '"You want to tell me, and I have no objection to hearing it."',
      'This was invitation enough.',
    ],
  },
  {
    chapter: 'Chapter 1',
    paragraphs: [
      '"Why, my dear, you must know, Mrs. Long says that Netherfield is taken by a young man of large fortune from the north of England; that he came down on Monday in a chaise and four to see the place, and was so much delighted with it that he agreed with Mr. Morris immediately; that he is to take possession before Michaelmas, and some of his servants are to be in the house by the end of next week."',
      '"What is his name?"',
      '"Bingley."',
      '"Is he married or single?"',
      '"Oh! single, my dear, to be sure! A single man of large fortune; four or five thousand a year. What a fine thing for our girls!"',
      '"How so? How can it affect them?"',
      '"My dear Mr. Bennet," replied his wife, "how can you be so tiresome! You must know that I am thinking of his marrying one of them."',
      '"Is that his design in settling here?"',
    ],
  },
  {
    chapter: 'Chapter 1',
    paragraphs: [
      '"Design! Nonsense, how can you talk so! But it is very likely that he may fall in love with one of them, and therefore you must visit him as soon as he comes."',
      '"I see no occasion for that. You and the girls may go, or you may send them by themselves, which perhaps will be still better; for as you are as handsome as any of them, Mr. Bingley might like you the best of the party."',
      '"My dear, you flatter me. I certainly have had my share of beauty, but I do not pretend to be anything extraordinary now. When a woman has five grown-up daughters, she ought to give over thinking of her own beauty."',
      '"In such cases, a woman has not often much beauty to think of."',
      '"But, my dear, you must indeed go and see Mr. Bingley when he comes into the neighbourhood."',
      '"It is more than I engage for, I assure you."',
      '"But consider your daughters. Only think what an establishment it would be for one of them. Sir William and Lady Lucas are determined to go, merely on that account, for in general, you know, they visit no newcomers."',
    ],
  },
  {
    chapter: 'Chapter 2',
    paragraphs: [
      'Mr. Bennet was among the earliest of those who waited on Mr. Bingley. He had always intended to visit him, though to the last always assuring his wife that he should not go; and till the evening after the visit was paid she had no knowledge of it.',
      'It was then disclosed in the following manner. Observing his second daughter employed in trimming a hat, he suddenly addressed her with—',
      '"I hope Mr. Bingley will like it, Lizzy."',
      '"We are not in a way to know what Mr. Bingley likes," said her mother resentfully, "since we are not to visit."',
      '"But you forget, mamma," said Elizabeth, "that we shall meet him at the assemblies, and that Mrs. Long has promised to introduce him."',
      '"I do not believe Mrs. Long will do any such thing. She has two nieces of her own. She is a selfish, hypocritical woman, and I have no opinion of her."',
    ],
  },
];

const TOC = [
  { ch: 1, title: 'Chapter 1', page: 1, active: true },
  { ch: 2, title: 'Chapter 2', page: 8 },
  { ch: 3, title: 'Chapter 3', page: 17 },
  { ch: 4, title: 'Chapter 4', page: 26 },
  { ch: 5, title: 'Chapter 5', page: 34 },
  { ch: 6, title: 'Chapter 6', page: 41 },
  { ch: 7, title: 'Chapter 7', page: 52 },
  { ch: 8, title: 'Chapter 8', page: 61 },
  { ch: 9, title: 'Chapter 9', page: 72 },
  { ch: 10, title: 'Chapter 10', page: 81 },
  { ch: 11, title: 'Chapter 11', page: 92 },
  { ch: 12, title: 'Chapter 12', page: 99 },
];

const SAMPLE_HIGHLIGHTS = [
  { id: 'h1', color: 'yellow', chapter: 'Chapter 1', page: 1,
    text: 'It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife.',
    note: 'Opening — sets the entire tone of the novel in one sentence.',
    date: 'Apr 12' },
  { id: 'h2', color: 'pink', chapter: 'Chapter 3', page: 19,
    text: 'She is tolerable, but not handsome enough to tempt me.',
    note: '',
    date: 'Apr 14' },
  { id: 'h3', color: 'green', chapter: 'Chapter 6', page: 47,
    text: 'Happiness in marriage is entirely a matter of chance.',
    note: 'Charlotte\'s view — interesting counterpoint to Elizabeth.',
    date: 'Apr 18' },
  { id: 'h4', color: 'blue', chapter: 'Chapter 1', page: 2,
    text: 'You want to tell me, and I have no objection to hearing it.',
    note: '',
    date: 'Apr 12' },
];

Object.assign(window, { BOOKS, PP_PAGES, TOC, SAMPLE_HIGHLIGHTS });
