// Purpose: Deterministic, collision-resistant, reversible mapping between arbitrary MCP server tool names
// and model-provider-safe tool identifiers (conforming to ^[a-zA-Z0-9_-]{1,64}$).

import Foundation

struct MCPToolNameMapper: Sendable {
    private static let prefix = "mcp_"

    /// Maps a profile ID and remote tool name into a model-safe tool name.
    /// Format: "mcp_<profile8Prefix>_<sanitizedToolName>" (clamped to 64 chars).
    static func toModelSafeName(profileID: UUID, originalToolName: String) -> String {
        let prefix8 = String(profileID.uuidString.replacingOccurrences(of: "-", with: "").prefix(8))
        let sanitizedTool = sanitizeName(originalToolName)
        let candidate = "\(prefix)\(prefix8)_\(sanitizedTool)"
        if candidate.count <= 64 {
            return candidate
        }
        return String(candidate.prefix(64))
    }

    /// Checks if a tool name was generated by this mapper.
    static func isMCPToolName(_ name: String) -> Bool {
        name.starts(with: prefix)
    }

    /// Extracts the 8-character profile prefix from a model-safe tool name.
    static func profilePrefix(from modelSafeName: String) -> String? {
        guard isMCPToolName(modelSafeName) else { return nil }
        let withoutPrefix = String(modelSafeName.dropFirst(prefix.count))
        let parts = withoutPrefix.split(separator: "_")
        guard let first = parts.first, first.count == 8 else { return nil }
        return String(first)
    }

    private static func sanitizeName(_ name: String) -> String {
        var result = ""
        for scalar in name.unicodeScalars {
            if CharacterSet.alphanumerics.contains(scalar) || scalar == "_" || scalar == "-" {
                result.append(Character(scalar))
            } else {
                result.append("_")
            }
        }
        return result.isEmpty ? "tool" : result
    }
}
